### ISSUE TITLE
koyeb上部署以后argo通道没有取得

### ISSUE THREAD

**Issue by Neomanbeta** [fscarmen2/Argo-X-Container-PaaS#12]
readme里的koyeb部分的导出节点数据截图里，可以看到伪装域名部分都可以看到argo的地址，但是我在第一次部署这个的时候伪装域名部分就只显示ARGO DOMAIN字样，看到昨天更新以后，我又重新部署了一次，依然是一样的结果，下面是我的节点信息，只是更改了UUID，其它部分没动
- {name: Argo-Vless, type: vless, server: icook.hk, port: 443, uuid: 隐藏, tls: true, servername: Argo domain, skip-cert-verify: false, network: ws, ws-opts: {path: /argo-vless?ed=2048, headers: { Host: Argo domain}}, udp: true}
可以看到servername和Host都只显示Argo domain，并没有显示readme里类似的multiple-lo-replies-formula.trycloudflare.com这样的域名。
虽然我把我的koyeb的二级域名写到这部分也可以使用节点，但是我还是想问一下，这个应该是有问题的吧？

**Comment by fscarmen2** [comment]
用 koyeb 给的网址，加上 `/list` 来看，如果你没有设置过用户名和密码，默认是 admin / password

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/92626977/226228133-e17cb563-c30b-42e8-9273-98e5955a196d.png">



> * 虽然我把我的koyeb的二级域名写到这部分也可以使用节点

虽然 koyeb  支持 cf cdn，这个没有 argo 那么效果好。

**Comment by Neomanbeta** [comment]
我上面的帖子里复制的其实就是list里的输出结果，可能我表述的不是很清楚吧。部署的时候我按照readme里做的，我只更改了WEB_PASSWORD，我把list的截图贴一下吧，看HOST和SNI部分就会知道我说的区别在哪了。
![QQ截图20230320145850](https://user-images.githubusercontent.com/33118244/226269225-901cb477-10d5-43ed-bc5f-c7f8028ada4d.png)

**Comment by fscarmen2** [comment]
> 我上面的帖子里复制的其实就是list里的输出结果，可能我表述的不是很清楚吧。部署的时候我按照readme里做的，我只更改了WEB_PASSWORD，我把list的截图贴一下吧，看HOST和SNI部分就会知道我说的区别在哪了。
> 
> ![QQ截图20230320145850](https://user-images.githubusercontent.com/33118244/226269763-ed167e5f-f858-4989-95ec-58f8665c3b16.png)

看你的图应该设置错误了，如果你用固定域名的，ARGO_DOMAIN 就应该填你的域名，如果你使用临时的，这个变量就不用填，看你应该是用了 ARGO_DOMIAN , 并且值为 Argo domain ，如果你是koyeb 的，用我的链接进去搭建的，而你又没有做固定域名，就把 ARGO_DOMAIN 和  ARGO_AUTH 两个变量删除再重新搭建即可

**Comment by Neomanbeta** [comment]
明白了，因为我看到readme里面写着这两个参数不是必须填写，所以我就没有去清空默认的数值，也没有去删除这两个变量，这两个变量默认是有数值的，其中ARGO_AUTH的数值就是ARGO DOMAIN，看来是我理解有误，多谢解答。
