### ISSUE TITLE
经常性的无法连接

### ISSUE THREAD

**Issue by laboratorys** [fscarmen2/Argo-X-Container-PaaS#13]
换了几个平台都差不多，应该是argo隧道的问题，不知道如何优化

**Comment by laboratorys** [comment]
同一时刻argo的隧道域名是可以正常访问

**Comment by xiaozhiob** [comment]
> 换了几个平台都差不多，应该是argo隧道的问题，不知道如何优化

你要去多看他几个项目，然后对比一下readme文件，项目支持绑定自己固定的cf argo隧道的，你没有设置，项目就给你随机了，随机的话过一段时间就会变
