### ISSUE TITLE
Railway容器搭建完成后Logs没有输出节点链接等信息

### ISSUE THREAD

**Issue by Ropgrc** [fscarmen2/Argo-X-Container-PaaS#2]
如标题，没有输出节点链接信息，无法将节点导入代理软件。
使用的项目是作者最新提交的项目，我记得前一个项目还能正常输出节点链接。

**Comment by fscarmen2** [comment]
这个新点的项目更科学啊，网址/list 这样随时看，火车头的效果很好

**Comment by Ropgrc** [comment]
> 这个新点的项目更科学啊，网址/list 这种随时候看，火车头的效果很好

这个网址是指哪个网址，我试了试digitalocean.com/list不行，这方面确实不懂。

**Comment by fscarmen2** [comment]
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/92626977/216819298-4144a0cd-885e-4f5d-ba22-917050df66e4.png">

**Comment by Ropgrc** [comment]
> <img alt="image" width="1637" src="https://user-images.githubusercontent.com/92626977/216819298-4144a0cd-885e-4f5d-ba22-917050df66e4.png">

![Snipaste_2023-02-05_20-49-47](https://user-images.githubusercontent.com/122720657/216819767-3c826f5f-375d-43fa-a8d1-089a202c0356.jpg)

**Comment by fscarmen** [comment]
你需要加个环境变量 PORT 为 3000，再重新部署了，记得全部为大写
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/62703343/216821488-6aeedac1-1929-43ed-a5f3-e664d43ebe7f.png">
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/62703343/216821521-5b1bbdda-9e8c-4b9d-813c-c9034e71be83.png">

**Comment by Ropgrc** [comment]
> 你需要加个环境变量 PORT 为 3000，再重新部署了，记得全部为大写 <img alt="image" width="1402" src="https://user-images.githubusercontent.com/62703343/216821488-6aeedac1-1929-43ed-a5f3-e664d43ebe7f.png"> <img alt="image" width="1105" src="https://user-images.githubusercontent.com/62703343/216821521-5b1bbdda-9e8c-4b9d-813c-c9034e71be83.png">

我等了一会，发现作者还没有回复，我就打开server.js把port常量改成const port = process.env.PORT || 3000;保存重新部署问题就解决了，不过谢谢作者的解答。

**Comment by Ropgrc** [comment]
PRO把这个issue关闭吧。
