### ISSUE TITLE
为什么生成的节点只有小火箭能用啊😂……

### ISSUE THREAD

**Issue by Benjamin1919** [fscarmen2/Argo-X-Container-PaaS#21]
平台：Koyeb
镜像：docker.io/fscarmen/argo-x
Argo隧道获取途径：https://fscarmen.cloudflare.now.cc/
Koyeb暴露端口：3000，协议是HTTP

现象：
1. 哪吒探针正常；
2. 小火箭导入vless/vmess/trojan/ss全部正常连接，icook.hk或www.digitalocean.com全部正常连接。手机流量/家庭宽带全部正常连接；
3. 但是软路由上的Passwall2和win11上的V2rayN全都不能连接，已确认每个参数都没错误

目前猜测可能的原因是passwall2和v2rayN都是用官方的xray-core1.8.3运行的，而小火箭是自己的内核，目前也找不出小火箭内核有什么独到之处😭

求大神指明排查方向，这也太匪夷所思了

**Comment by Benjamin1919** [comment]
2023/08/11更新：
貌似是目标地址的原因，vless一直连不上icook.hk，偶尔能连上www.digitalocean.com；
经过多次尝试后vmess/trojan/ss都能连上icook.hk和www.digitalocean.com；

推测是域名解析的问题或者被阻断。

请问是不是理论上目标地址可以填任何套用了cloudflare CDN的网址啊？

**Comment by fscarmen2** [comment]
你小火箭能使用，说明节点是没有问题了，至于为什么用了，有可能软路由用另外的运营商，同样的优选或者sni阻断了，你可以试着换个优选，又或者换个argo域名，我想到就是这两个原因而已

**Comment by Benjamin1919** [comment]
> 你小火箭能使用，说明节点是没有问题了，至于为什么用了，有可能软路由用另外的运营商，同样的优选或者sni阻断了，你可以试着换个优选，又或者换个argo域名，我想到就是这两个原因而已

谢谢大佬～另外再问一下，节点速度还挺快的，这是因为Koyeb服务器的速度快还是因为Argo隧道的速度快呢😁

**Comment by fscarmen2** [comment]
都有关系的，也写你使用的优选IP或者域名快有关的，不是单一个因素决定的。
