### ISSUE TITLE
web进程为什么起不来呢？使用的是zeabur

### ISSUE THREAD

**Issue by nwfnyfgvfir** [fscarmen2/Argo-X-Container-PaaS#27]
获取守护进程和系统进程表：
┌────┬─────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name    │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1  │ argo    │ default     │ N/A     │ fork    │ 79       │ 45s    │ 0    │ online    │ 0%       │ 34.9mb   │ root     │ disabled │
│ 0  │ web     │ default     │ N/A     │ fork    │ 0        │ 0      │ 15   │ errored   │ 0%       │ 0b       │ root     │ disabled │
└────┴─────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  8 09:43 ?        00:00:04 node server.js
root          64       1  1 09:43 ?        00:00:00 PM2 v5.3.0: God Daemon (/root/.pm2)
root          79      64  0 09:43 ?        00:00:00 /usr/local/bin/cloudflared tunnel --edge-ip-version auto --config tunnel.yml run
root         210       1  0 09:43 ?        00:00:00 /bin/sh -c pm2 list; ps -ef
root         221     210  0 09:43 ?        00:00:00 ps -ef

**Comment by fscarmen** [comment]
建议停了项目，该平台封的，TOS。

**Comment by fscarmen2** [comment]
建议停了项目，该平台封的，TOS。

**Comment by nwfnyfgvfir** [comment]
好的，谢谢
