### ISSUE TITLE
大佬，不行啊，部署到doprax以后，取不到argo的地址，而且改了uuid以后也没生效

### ISSUE THREAD

**Issue by lovelygfj** [fscarmen2/Argo-X-Container-PaaS#9]

**Comment by fscarmen2** [comment]
doprax现在炸了，换别的平台吧

**Comment by lovelygfj** [comment]
用了您最新更新的脚本以后，首次运行不成功，好像还是argo没运行起来。
需要在terminal里重新 bash argo.sh以后才行。

**Comment by fscarmen** [comment]
应该不会的啊，自动运行的，下次你部署时再看看，如仍然有问题，告诉我，我看看！

**Comment by fscarmen2** [comment]
应该不会的啊，自动运行的，下次你部署时再看看，如仍然有问题，告诉我，我去现场看看！

**Comment by fscarmen** [comment]
我今天才运行了一个全新的，没有问题啊

**Comment by fscarmen2** [comment]
官方的确很不稳定，域名不能正确访问（不是被墙），官方的 open shell 也使用不了。

![image](https://user-images.githubusercontent.com/92626977/221065428-a5025e0f-7587-43ee-8ddc-2f74d2adc2ea.png)

**Comment by Neomanbeta** [comment]
> 我今天才运行了一个全新的，没有问题啊

我也碰到了和楼主一模一样的问题。
我新建的话，argo就起不来，反复删除多次重试多次也是一样，而且web是有时候能起来，有时候起不来。
argo起不来的话，host和sni就都是空的。
最后也是按照楼主的提示，在shell里bash argo.sh才能获得正常的节点链接。
虽然说现在doprax抽风，但是我用[fscarmen2/Argo-Xray-PaaS](https://github.com/fscarmen2/Argo-Xray-PaaS)部署就一点问题没有。
希望大佬能抽空看看到底是什么造成的，多谢。
